### ISSUE TITLE
WiFi provisioning using esp32p4 and C6 with BLE (EHM-111)

### ISSUE THREAD

**Issue by ohmtech-rdi** [espressif/esp-hosted-mcu#108]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [x] Described the feature in detail and justified the reason for the request.
- [x] Provided specific use cases and examples.

### Feature description

Hi, is there any example on how to make the [WiFi Provisioning example](https://github.com/espressif/esp-idf/tree/v5.5.1/examples/provisioning/wifi_prov_mgr) work in esp32p4 dev kit with C6 and BLE?

### Use cases

WiFi configuration on a headless device (with P4 and C6 like the P4 eval board) using QR-code and BLE.

### Additional context

We used the [Wifi Provisioning example](https://github.com/espressif/esp-idf/tree/v5.5.1/examples/provisioning/wifi_prov_mgr) and added required component dependencies `esp-hosted` and `esp-wifi-remote` as described in the [two-chip solution](https://github.com/espressif/esp-idf/blob/v5.5.1/examples/wifi/README.md#wi-fi-examples-with-two-chip-solution).

The example doesn't build because of missing symbols for `wifi_provisioning` (while listed in CMakeLists `PRIV_REQUIRES`), but I guess that `wifi_provisioning` would need to be wrapper around the commands that the C6 will effectively execute, and I guess it is not implemented yet, or this is not the right method.

Apparently, `wifi_provisioning` is deprecated in favor of the `espressif/network_provisioning` component, but the latter [`wifi_prov` example](https://github.com/espressif/idf-extra-components/tree/master/network_provisioning/examples/wifi_prov) doesn't have the ESP32-P4 listed in its supported targets either.

We are a small company, and this is our first ESP32 project (but we have extended experience with STM, ie this is not our first embedded project), so we can't really afford to spend ressources (spend a month or pay an expert) on that first evaluation spike.

I see on [this recent issue](https://github.com/espressif/esp-hosted-mcu/issues/43) that DPP is scheduled first, so we are wondering if WiFi provisioning using BLE is in your backlog, and when is a rough estimate on when it will be available and considered stable.

Thanks for your hard work!

**Comment by mantriyogesh** [comment]
Hello @ohmtech-rdi,

The Wi-Fi provisioning example may not be straightforward to adapt directly, as host Wi-Fi calls need to be supported in a manner similar to standard Wi-Fi commands. In this setup, the Bluetooth host stack runs on the P4, while the C6 acts as the BLE controller. This should be feasible, and we will review it on our side and provide feedback.

In the meantime, could you please share the example along with the textual errors you encountered? If it’s something simple, we may be able to provide quick guidance.

Additionally, we will look into adding this scenario to the host examples so that it becomes directly usable for users.

---

@SohKamYung-Espressif PTAL.

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh,

Thanks for your reply and looking into it.

Please find below a portion of the build log with the missing symbols for `wifi_provisioning`:

```
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:236:(.text.app_main+0xfc): undefined reference to `WIFI_PROV_EVENT'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:253:(.text.app_main+0x228): undefined reference to `wifi_prov_scheme_ble_event_cb_free_btdm'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:253:(.text.app_main+0x22c): undefined reference to `wifi_prov_scheme_ble_event_cb_free_btdm'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:253:(.text.app_main+0x236): undefined reference to `wifi_prov_scheme_ble'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:253:(.text.app_main+0x23a): undefined reference to `wifi_prov_scheme_ble'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:266:(.text.app_main+0x280): undefined reference to `wifi_prov_mgr_init'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:267:(.text.app_main+0x2be): undefined reference to `wifi_prov_mgr_is_provisioned'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:278:(.text.app_main+0x314): undefined reference to `wifi_prov_scheme_ble_set_service_uuid'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:300:(.text.app_main+0x368): undefined reference to `wifi_prov_mgr_endpoint_create'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:302:(.text.app_main+0x378): undefined reference to `wifi_prov_mgr_start_provisioning'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:315:(.text.app_main+0x3ce): undefined reference to `wifi_prov_mgr_reset_provisioning'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:271:(.text.app_main+0x40e): undefined reference to `wifi_prov_mgr_endpoint_register'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:271:(.text.app_main+0x416): undefined reference to `wifi_prov_mgr_wait'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:272:(.text.app_main+0x41e): undefined reference to `wifi_prov_mgr_deinit'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:324:(.text.app_main+0x462): undefined reference to `wifi_prov_mgr_deinit'
```

The `CMakeLists.txt` I used:
```
idf_component_register(
   SRCS "main.cpp"
   PRIV_REQUIRES esp_wifi nvs_flash wifi_provisioning
   INCLUDE_DIRS ""
)
```

The `idf_component.yml` I used:
```
dependencies:
  espressif/esp_wifi_remote:
    version: ">=0.10,<2.0"
  espressif/esp_hosted:
    version: "~2"
```

Portions of `sdkconfig.defaults` I used, relevant to the project:
```
CONFIG_BT_ENABLED=y
CONFIG_BTDM_CTRL_MODE_BLE_ONLY=y
CONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=n
CONFIG_BTDM_CTRL_MODE_BTDM=n
CONFIG_BT_NIMBLE_ENABLED=y
CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_2=y
```

In the meantime I realised that [`espressif/network_provisioning`](https://github.com/espressif/idf-extra-components/tree/master/network_provisioning) can actually work with v5.5 (and not only v6). It will link, but running won't work after.

This just to say that maybe some work has been done already in that direction. I see that P4 support has been added at least to the [change log of v1.1.0](https://components.espressif.com/components/espressif/network_provisioning/versions/1.1.0/changelog?language=), but their example `wifi_prov` still doesn't work, but maybe for another reason though that I didn't have the time to investigate yet.

Thanks!

**Comment by mantriyogesh** [comment]
```
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:272:(.text.app_main+0x41e): undefined reference to `wifi_prov_mgr_deinit'
.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: wifi_config/main/main.cpp:324:(.text.app_main+0x462): undefined reference to `wifi_prov_mgr_deinit'
```

I see this issue coming, because wifi_provisioning component itself not present in esp-idf and is getting replaced by `network_provisioning` through the registry component (as you already pointed)

I have a question, as you are interested to use BLE to do Wi-Fi provisioning, there are two options - 

1. P4 actively uses Bluetooth
P4 uses Bluetooth stack and control C6's BLE controller using HCI interface. 
But P4 later want to retain the control of C6 BLE

2. BLE only for provisioning, can be just get it done on C6.
BLE is only for provisiong, later point, P4 doesn't care of Bluetooth as such.

Can you please let me know which option suites your use case?

**Comment by mantriyogesh** [comment]
for option 1, I have created PR for`network_provisioning` at https://github.com/espressif/idf-extra-components/pull/584.
I have not tested this, but builds fine. Can you please try this once?

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

Sorry for the late reply, I had to switch to another project in the meantime.

In the story I'm working on, we are only using BLE for provisioning and only WiFi after. So the option would be number 2.
Also as far as we understood, getting simultaneously WiFi and BLE to work on the same C6 module is not straightforward, so I think the current story will stay relevant for the rest of our product timeline.

For option 1, I'll have a look at the PR and test it this week. Thanks!

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

So I could finally give it a go. I first tried in my story, by porting the differences from the PR [espressif/idf-extra-components#584](https://github.com/espressif/idf-extra-components/pull/584).

It built correctly, but when I run, I had several crashes, but after a few automatic reboots, then it started to work. Not sure why.
I'm also not sure if there is anything related to my project, but I'm really not sure, since this happens quite early.
I then restarted the board multiple times to try to reproduce the first crashes, but the problem "disappeared".

Please find below the crashes, from where in the log it started to diverge from the working case, which seems to be always on an error, and with a few lines of context before. You can find the [full log here](https://github.com/user-attachments/files/22950558/log-wifi-prov.txt).

<details>
<summary>First crash</summary>

```
TUPLE: CFTABLE_ENTRY, size: 8
  INDX: C1, Intface: 1, Default: 1, Conf-Entry-Num: 1
  IF: 41
  FS: 30, misc: 0, mem_space: 1, irq: 1, io_space: 0, timing: 0, power: 0
  IR: 30, mask: 1,   IRQ: FF FF
  LEN: FFFF
TUPLE: END
E (1929) sdio_wrapper: sdio_cared_fn_init failed
E (1929) H_SDIO_DRV: card init failed
I (1929) transport: Waiting for esp_hosted slave to be ready
I (2029) H_SDIO_DRV: SDIO Host operating in STREAMING MODE
I (2029) H_SDIO_DRV: Open data path at slave
Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.

Core  0 register dump:
--- Stack dump detected
MEPC    : 0x400398e2  RA      : 0x4003736e  SP      : 0x4ff1beb0  GP      : 0x4ff11500  
--- 0x400398e2: sdmmc_send_cmd at .espressif/esp-idf/components/sdmmc/sdmmc_cmd.c:15
--- 0x4003736e: sdmmc_io_rw_direct at .espressif/esp-idf/components/sdmmc/sdmmc_io.c:270
TP      : 0x4ff1bfd0  T0      : 0x4fc0a9f8  T1      : 0x20000000  T2      : 0x00000000  
S0/FP   : 0x4ff1bec4  S1      : 0x00000000  A0      : 0x00000000  A1      : 0x4ff1bec4  
A2      : 0x98011800  A3      : 0x88000000  A4      : 0x4ff1bf1f  A5      : 0x98011801  
A6      : 0x4000a2de  A7      : 0x0000000a  S2      : 0x0000008c  S3      : 0x4ff1bf5f  
--- 0x4000a2de: usb_serial_jtag_write at .espressif/esp-idf/components/esp_driver_usb_serial_jtag/src/usb_serial_jtag_vfs.c:184
S4      : 0x00000000  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x00000000  T4      : 0x00000000  T5      : 0x00000000  T6      : 0x00000000  
MSTATUS : 0x00011880  MTVEC   : 0x4ff00003  MCAUSE  : 0x00000005  MTVAL   : 0x00000040  
--- 0x4ff00003: _vector_table at ??:?
MHARTID : 0x00000000  


--- Backtrace:


add symbol table from file "wifi_config/artifacts/bootloader/bootloader.elf"
sdmmc_send_cmd (card=card@entry=0x0, cmd=cmd@entry=0x4ff1bec4) at .espressif/esp-idf/components/sdmmc/sdmmc_cmd.c:15
15	    if (card->host.command_timeout_ms != 0) {
#0  sdmmc_send_cmd (card=card@entry=0x0, cmd=cmd@entry=0x4ff1bec4) at .espressif/esp-idf/components/sdmmc/sdmmc_cmd.c:15
#1  0x4003736e in sdmmc_io_rw_direct (card=card@entry=0x0, func=func@entry=1, reg=reg@entry=140, arg=<optimized out>, arg@entry=2281701376, byte=byte@entry=0x4ff1bf1f "\001\001") at .espressif/esp-idf/components/sdmmc/sdmmc_io.c:269
#2  0x400376e2 in sdmmc_io_write_byte (card=card@entry=0x0, function=function@entry=1, addr=addr@entry=140, in_byte=<optimized out>, out_byte=out_byte@entry=0x0) at .espressif/esp-idf/components/sdmmc/sdmmc_io.c:295
#3  0x400218fe in hosted_sdio_write_reg (ctx=<optimized out>, reg=140, data=0x4ff1bf5f "\001\020/\r@\255\001", size=<optimized out>, lock_required=<optimized out>) at wifi_config/managed_components/espressif__esp_hosted/host/port/esp/freertos/src/port_esp_hosted_host_sdio.c:509
#4  0x4001e720 in sdio_generate_slave_intr (intr_no=intr_no@entry=0 '\000') at wifi_config/managed_components/espressif__esp_hosted/host/drivers/transport/sdio/sdio_drv.c:305
#5  0x4001ed00 in sdio_read_task (pvParameters=<error reading variable: value has been optimized out>) at wifi_config/managed_components/espressif__esp_hosted/host/drivers/transport/sdio/sdio_drv.c:1000
#6  0x4ff06e2a in vPortTaskWrapper (pxCode=<optimized out>, pvParameters=<optimized out>) at .espressif/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:255
```

</details>

<details>
<summary>All the other crashes (3 times)</summary>

```
I (1631) sdio_wrapper: SDIO master: Slot 1, Data-Lines: 4-bit Freq(KHz)[40000 KHz]
I (1631) sdio_wrapper: GPIOs: CLK[18] CMD[19] D0[14] D1[15] D2[16] D3[17] Slave_Reset[54]
I (1631) sdio_wrapper: Queues: Tx[20] Rx[20] SDIO-Rx-Mode[1]
E (1661) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
HINT: Please reboot the board and then try again
E (1661) sdio_wrapper: sdmmc_card_init failed
E (1661) H_SDIO_DRV: card init failed
I (1661) transport: Waiting for esp_hosted slave to be ready
I (1711) H_SDIO_DRV: SDIO Host operating in STREAMING MODE
I (1711) H_SDIO_DRV: Open data path at slave
Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.

Core  0 register dump:
--- Stack dump detected
MEPC    : 0x400398e2  RA      : 0x4003736e  SP      : 0x4ff1beb0  GP      : 0x4ff11500  
--- 0x400398e2: sdmmc_send_cmd at .espressif/esp-idf/components/sdmmc/sdmmc_cmd.c:15
--- 0x4003736e: sdmmc_io_rw_direct at .espressif/esp-idf/components/sdmmc/sdmmc_io.c:270
TP      : 0x4ff1bfd0  T0      : 0x4fc0a9f8  T1      : 0x10000000  T2      : 0x00000000  
S0/FP   : 0x4ff1bec4  S1      : 0x00000000  A0      : 0x00000000  A1      : 0x4ff1bec4  
A2      : 0x98011800  A3      : 0x88000000  A4      : 0x4ff1bf1f  A5      : 0x98011801  
A6      : 0x4000a2de  A7      : 0x0000000a  S2      : 0x0000008c  S3      : 0x4ff1bf5f  
--- 0x4000a2de: usb_serial_jtag_write at .espressif/esp-idf/components/esp_driver_usb_serial_jtag/src/usb_serial_jtag_vfs.c:184
S4      : 0x00000000  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x00000000  T4      : 0x00000000  T5      : 0x00000000  T6      : 0x00000000  
MSTATUS : 0x00011880  MTVEC   : 0x4ff00003  MCAUSE  : 0x00000005  MTVAL   : 0x00000040  
--- 0x4ff00003: _vector_table at ??:?
MHARTID : 0x00000000  


--- Backtrace:


add symbol table from file "wifi_config/artifacts/bootloader/bootloader.elf"
sdmmc_send_cmd (card=card@entry=0x0, cmd=cmd@entry=0x4ff1bec4) at .espressif/esp-idf/components/sdmmc/sdmmc_cmd.c:15
15	    if (card->host.command_timeout_ms != 0) {
#0  sdmmc_send_cmd (card=card@entry=0x0, cmd=cmd@entry=0x4ff1bec4) at .espressif/esp-idf/components/sdmmc/sdmmc_cmd.c:15
#1  0x4003736e in sdmmc_io_rw_direct (card=card@entry=0x0, func=func@entry=1, reg=reg@entry=140, arg=<optimized out>, arg@entry=2281701376, byte=byte@entry=0x4ff1bf1f "\001\001") at .espressif/esp-idf/components/sdmmc/sdmmc_io.c:269
#2  0x400376e2 in sdmmc_io_write_byte (card=card@entry=0x0, function=function@entry=1, addr=addr@entry=140, in_byte=<optimized out>, out_byte=out_byte@entry=0x0) at .espressif/esp-idf/components/sdmmc/sdmmc_io.c:295
#3  0x400218fe in hosted_sdio_write_reg (ctx=<optimized out>, reg=140, data=0x4ff1bf5f "\001\020/\r@\233\001", size=<optimized out>, lock_required=<optimized out>) at wifi_config/managed_components/espressif__esp_hosted/host/port/esp/freertos/src/port_esp_hosted_host_sdio.c:509
#4  0x4001e720 in sdio_generate_slave_intr (intr_no=intr_no@entry=0 '\000') at wifi_config/managed_components/espressif__esp_hosted/host/drivers/transport/sdio/sdio_drv.c:305
#5  0x4001ed00 in sdio_read_task (pvParameters=<error reading variable: value has been optimized out>) at wifi_config/managed_components/espressif__esp_hosted/host/drivers/transport/sdio/sdio_drv.c:1000
#6  0x4ff06e2a in vPortTaskWrapper (pxCode=<optimized out>, pvParameters=<optimized out>) at .espressif/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:255
```

</details>

<details>
<summary>The working case at the end</summary>

```
TUPLE: CFTABLE_ENTRY, size: 8
  INDX: C1, Intface: 1, Default: 1, Conf-Entry-Num: 1
  IF: 41
  FS: 30, misc: 0, mem_space: 1, irq: 1, io_space: 0, timing: 0, power: 0
  IR: 30, mask: 1,   IRQ: FF FF
  LEN: FFFF
TUPLE: END
I (1711) sdio_wrapper: Function 0 Blocksize: 512
I (1711) sdio_wrapper: Function 1 Blocksize: 512
I (1711) H_SDIO_DRV: Card init success, TRANSPORT_RX_ACTIVE
I (1721) transport: set_transport_state: 1
I (1721) transport: Waiting for esp_hosted slave to be ready
I (1811) H_SDIO_DRV: SDIO Host operating in STREAMING MODE
I (1811) H_SDIO_DRV: Open data path at slave
I (1811) H_SDIO_DRV: Starting SDIO process rx task
I (1811) H_SDIO_DRV: Received ESP_PRIV_IF type message
I (1811) transport: Received INIT event from ESP32 peripheral
I (1821) transport: EVENT: 12
I (1821) transport: Identified slave [esp32c6]
I (1821) transport: EVENT: 11
I (1831) transport: capabilities: 0xd
I (1831) transport: Features supported are:
I (1831) transport: 	 * WLAN
I (1841) transport: 	   - HCI over SDIO
I (1841) transport: 	   - BLE only
I (1841) transport: EVENT: 13
```

</details>

In the working case at the end, I also had this warning:
```
W (1851) transport: === ESP-Hosted Version Warning ===
Version on Host is NEWER than version on co-processor
RPC requests sent by host may encounter timeout errors
or may not be supported by co-processor
W (1861) transport: === ESP-Hosted Version Warning ===
I (1871) transport: ESP board type is : 13 
```

Unfortunately, OTA is not yet in that story, and I don't have a programmer to flash the C6 directly, as advised in [those instructions](https://github.com/espressif/esp-hosted-mcu/blob/main/examples/host_performs_slave_ota/README.md)

I then tried using PR [espressif/idf-extra-components#584](https://github.com/espressif/idf-extra-components/pull/584)
```
git clone https://github.com/mantriyogesh/idf-extra-components.git
cd idf-extra-components/network_provisioning/examples/wifi_prov
source .espressif/esp-idf/export.sh
idf.py set-target esp32p4
idf.py menuconfig
# Component config → Wi-Fi Remote → choose slave target and select esp32c6
# (was already selected)
idf.py build
idf.py -p /dev/cu.usbmodem5A7A0370581 -b 115200 flash monitor
```
And it worked also. I tried the full scenario with the [ESP BLE provisioning iOS app](https://apps.apple.com/in/app/esp-ble-provisioning/id1473590141), and the provisioning worked.

Do you know why I got those crashes? And why it somehow auto-magically repaired itself? Thanks!

**Comment by mantriyogesh** [comment]
Hello @ohmtech-rdi ,

> Unfortunately, OTA is not yet in that story, and I don't have a programmer to flash the C6 directly

You already have hosted slave firmware (be any version). so you can directly do OTA update using LittleFS method in https://components.espressif.com/components/espressif/esp_hosted/examples/host_performs_slave_ota. You do not need extra hardware required.

The crash is after effect. Ideally sdio init shouldn't have failed.

```
E (1661) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
HINT: Please reboot the board and then try again
E (1661) sdio_wrapper: sdmmc_card_init failed
E (1661) H_SDIO_DRV: card init failed
```


The problem is that SDIO probe was failed. this is race condition, the probe from host was done little ahead, before slave completely boot up and expose sdio, leading to crash.

As a workaround, adding small delay in else condition here should delay the host little to ensure slave is fully boot up.

https://github.com/espressif/esp-hosted-mcu/blob/903c4d6acddb37c1e1f9e77bc6316bba47c960f0/host/drivers/transport/transport_drv.c#L173

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

Thanks for the pointer about C6 firmware update using OTA/LittleFS.

Thanks also for the workaround about the race condition. Our stories can be blocked for now, since they are mainly spikes for evaluation.

But if I understand well, you gave me a workaround (very appreciated, thanks!), but your team will fix this race condition, right?

**Comment by mantriyogesh** [comment]
Hello @ohmtech-rdi ,

Actually we used to have delay here (see this from slave reset triggered and then sdcard first time init triggered, logical code flow).

I tagged you here: https://github.com/espressif/esp-hosted-mcu/commit/c170b976df30f7a5aaa3c62c96d1cb325e4f7906#r168135495

As the issue is visible for your would you help to find optimal time in `g_h.funcs->_h_msleep()` ? I will add 100ms buffer to your value and push it in the code.

Also please confirm CONFIG_FREERTOS_HZ is 1000 in your sdkconfig?

**Comment by mantriyogesh** [comment]
Please add 'msleep' here instead:
https://github.com/espressif/esp-hosted-mcu/blob/903c4d6acddb37c1e1f9e77bc6316bba47c960f0/host/drivers/transport/sdio/sdio_drv.c#L1478

This is only then applicable for sdio.

- Why??
- This problem is not for spi/spi_hd/uart. they trigger data ready as interrupt.
- SDIO we do not want to waste just one gpio on this..

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

I can't see the tag in your first comment as the commit is too big for GitHub. However that seems to be unrelevant with your second comment.

I didn't indeed put `CONFIG_FREERTOS_HZ=1000` in my `sdkconfig` after reading [this comment](https://github.com/espressif/idf-extra-components/pull/584#discussion_r2416573009) on the PR. But I'll put it back as you advised.

I'll add `g_h.funcs->_h_msleep(100);` [here](https://github.com/espressif/esp-hosted-mcu/blob/903c4d6acddb37c1e1f9e77bc6316bba47c960f0/host/drivers/transport/sdio/sdio_drv.c#L1478) as suggested.

However, please note that I add the issue just the first time. I can't seem to be able to reproduce it (not that I tried a lot though).

I'll first try to see if I can find a pattern to retrigger the problem consistently, before I introduce the delay to avoid the race condition.

I'm thinking about calling `ctrl+T ctrl+R` to reset the target board many times in IDF monitor, until I get the crash.
Do you think this is a good approach?

**Comment by mantriyogesh** [comment]
Okay. thanks for all info.

> I'm thinking about calling ctrl+T ctrl+R to reset the target board many times in IDF monitor, until I get the crash.
Do you think this is a good approach?

I am not sure of this. you can do on/off on the board if it is esp32-Function-EV board. or press reset button of host.

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

So I first made the test to try to find a way to reproduce it before I would incorporate the sleep modification, by turning the board on and off again, as using the on-board RESET didn't seem to retrigger the problem. In the process I managed somehow to "brick it". It started somehow to work again after it was off for some time, but from then on nothing really made sense, I have random panics, even with base examples.

Adding just a sleep of 100ms seems to dit it before I started to have more random problems, so I'm not sure you can trust this value. After 100, 200 or 500 gave the same outcomes afterwards.

I must emphasis again that this our first ESP32 project, so maybe we are not the best assets to make this test. I really appreciate your trust to push the value in the code, but I couldn't really get to the pattern "reproduce problem, make fix, problem fixed, remove fix, reproduce problem, make fix, problem fixed".

I'll buy a new board to make sure I start fresh again, but I would appreciate (and I think it makes more sense) your team could do the test in the meantime.

Thanks again a lot for your help! Really appreciated.

**Comment by mantriyogesh** [comment]
100 msec is still pretty less value. 

Please add up 500msec.

> I must emphasis again that this our first ESP32 project, so maybe we are not the best assets to make this test. I really appreciate your trust to push the value in the code, but I couldn't really get to the pattern "reproduce problem, make fix, problem fixed, remove fix, reproduce problem, make fix, problem fixed".

I understand, Actually this problem not experienced at our side at all. but this SDIO card probing is happening from host to slave (which can very well fail), if not done after complete boot up of slave.
Even if just SDIO probe is successful, simply doesn't mean that all sdio functionality at slave are up, so despite early probing successful, will lead to some read/write operation failure, if done very early. 500 is comfortable value. if you do not experience any issues with 500ms, i will just that as fix.

> In the process I managed somehow to "brick it".

I am so sorry, that your board failed. Can you please send me the logs, if something I can help with, I can try to recover.

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

Thanks for helping again, but I preferred to buy a new board just in case, to make sure not to waste time. I received the new board yesterday so I'll run the tests again, but this time more carefully. I'll keep you updated on my findings.

**Comment by ohmtech-rdi** [comment]
Hi @mantriyogesh ,

Sorry for the late reply. I ordered instead cheaper variants for my tests ([Waveshare Nano](https://www.waveshare.com/esp32-p4-nano.htm)), and waited enough time in between each test run. 

I've run each test 100 times and stopped at the first error. I don't know if 100 times is enough as something like 2/3-9 reliability is quite low in particular for a race condition. I couldn't find a way to automate it so this has been very long.

Also my mistake, the USB ports on those small boards with a non-mounted connector are clearly not rated for so many insertions/removal, so they would break as well.

My results are that 500ms I had still an error, but couldn't capture it (the console just became unresponsive). Then I started at 10s and decreased by halfing the time each time. I stopped at 2.5s and this still worked after the 100th test. After that, my company asked me to stop.

I'm happy to test again if there is a way to automate it.

But now that's I've been more into the code, I don't even know if what I did made sense anyway. Any change to the co-processor firmware could change those values. Already on the main processor, I see that the boot time is clearly not consistent, and I guess there are some good reasons about it anyway (ie that's not a criticism).

> SDIO we do not want to waste just one gpio on this

I'm really not sure if this would be a waste, as, at least from a software developer point of view, that seems to be the only way to have a sane synchronisation between the 2 processors. Having "just" a 1% failure after an OTA update of the co-processor would be a totally no-go for our product. My company feels at the moment that this P4/C6 setup is either too complicated or not enough mature (we have completely overdue our second spike deadline) given our lack of expertise with the ESP32 environment.

I don't also know if the current dev board actually permits it anyway. When reading [the schematic for the dev board](https://dl.espressif.com/dl/schematics/esp32-p4-function-ev-board-schematics_v1.52.pdf) I can't seem to find any GPIOs apart from the SD pins used to connect the C6 and P4? Could the SD pins be used as GPIO before the SD communication itself is started?

Thanks!

**Comment by mantriyogesh** [comment]
Wow! Thats nice regression you did there. Thanks for helping out. 2.5s is too much IMO. Ideally slave shouldn't take such huge time to just get SDIO link up.

![Image](https://github.com/user-attachments/assets/e9a69361-dcc7-485c-8b1f-791b62030867)

There is one extra GPIO reserved for wake up (I think, it might not be used in your set up yet).


> My results are that 500ms I had still an error, but couldn't capture it
Can you please attach the error or full text logs at both sides, to understand exact what issue you run into.

Little off-topic, but still very much related:
The main problem is actually different however, need to give some time to solve it correctly.
In conventional Linux systems also, if you do not have card detection method, Linux are satted to 'poll' by introducing `broken-cd;` argument. however, adding GPIO as card detection is lot easier, hoever, it is not something within SDIO lines. That's story in Linux, which even valid in our Linux related repo. But having said that, Linux actually probes the ESP sdio multiple times till it successfully can enter to probing.

Coming back to MCU, As Host here is trying to probe the ESP SDIO, it can obviously fail, if such card detection GPIO is not available. however, even if the sdio probe failed, it should still retry the probing for several times, say if safe heaven is 2.5sec, i would still think of probing till 3 sec, till it finally give up (because, we have to give up some time).

In my opinion, after probing is failed, user should have option through Kconfig, to ignore (and use P4 or host, without hosted), or to assert (considering hosted is mandatory for the use case).

Having GPIO may help, but adding extra GPIO is very critical resource, specially in general solutions. If we can get into probing unless successful, is still the better way ahead, irrespective if we have GPIO for probing acknowledgement.

If you think  if `HIGH` GPIO from GPIO02 at C6 to GPIO 6 at P4, can help you to make reliable system, still can be done with small code change. Despite having said that, the SDIO should be given fair probing chance if failed, due to some temporary issues.

I would like to hear your views on the said case.
Also if feasible and if captured already, logs would ensure that we are solving correct problem..

**Comment by mantriyogesh** [comment]
There is one additional issue I had experienced in my testing, host probing gets successful in first go but when you make any read or write, still sometimes ends up in failure with 0x107 (sdio medium unavailable). Ideally such instance should not have occurred from lower HAL side. Because of this it makes mandatory to re-probe, if some read write operation had failed.

If or not using GPIO, still IMO `some` delay needs to be introduced before invoking first write towards slave from host, would be simple and lifesaver, by the time, this issue is not solved from HAL layers.

**Comment by ohmtech-rdi** [comment]
Ah sorry for the late reply, I didn't think you were actively waiting for my feedback.

I understand that using another GPIO wouldn't be really something possible for a general solution. From my point of view indeed, I need a reliable hardware to develop our software spikes while our own hardware is developed, and I (but I guess in general everybody) are using evaluation board exactly for that, as they are the reference hardware implementation.

Said differently, it is mandatory to me that the solution would work on the current P4 eval board of Espressif, and most probably also Waveshare one.

Indeed, if it's possible to retry probing the SD until it works, with a 3s timeout, seems fair to me. Even I think that if this would be blocking (ie not yield to other FreeRTOS tasks), that would still most likely still be ok for us.

**Comment by mantriyogesh** [comment]
I understood your explanation.
No, I am not blocked for your comment. I will add both approaches for simplicity.

1. GPIO based (basically kind of card detection)
2. Polling with configurable delay

(1) would be by default disabled from config, but should be able to easy configured in `idf.py menuconfig`
(2) By default the polling would be done, if configured to, with configurable delay


So this would be easily just be changed as user wishes to control. but please bear with me for the delay in implementation. I am in middle of some other work, once done , will pick this up next.
