### ISSUE TITLE
component does fail to compile with IDF branch release/v5.5 (EHM-86)

### ISSUE THREAD

**Issue by Jason2866** [espressif/esp-hosted-mcu#83]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

to compile successfully 

### Actual behavior (suspected bug)

it fails when trying to compile with Arduino Lib Builder

### Error logs or terminal output

```shell
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/managed_components/espressif__esp_hosted/host/drivers/bt/vhci_drv.c
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/managed_components/espressif__esp_hosted/host/drivers/bt/vhci_drv.c:47:9: error: expected ';' before 'int'
   47 | __WEAK__ int hci_rx_handler(interface_buffer_handle_t *buf_handle)
      |         ^~~~
      |         ;
```

### Steps to reproduce the behavior

espressif Arduino Lib Builder to compile 

### Project release version

latest

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Ubuntu 24.04

### Shell

ZSH

### Additional context

fixed by #84
